/*
 * 🪶 Hazel: Minimal, and fast HTTP proxy to host files from any cloud storage provider.
 * Copyright 2022-2023 Noelware <team@noelware.org>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.noelware.hazel.cli.commands

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.parameters.arguments.argument
import com.github.ajalt.clikt.parameters.types.file
import com.github.ajalt.mordant.terminal.Terminal
import org.noelware.hazel.cli.logger
import java.io.File

class GenerateConfigCommand(private val terminal: Terminal): CliktCommand(
    "Generates a configuration file in the specified destination",
    name = "generate-config"
) {
    private val dest: File by argument("dest").file(
        mustExist = false,
        canBeFile = true,
        canBeDir = false,
        mustBeWritable = true,
        mustBeReadable = true,
        canBeSymlink = true
    )

    override fun run() {
        terminal.logger.info("Writing configuration file in $dest")
        dest.writeBytes(
            """
        |# This configuration file was generated by `hazel generate-config`
        |storage:
        |  filesystem:
        |    directory: /var/lib/noelware/hazel/data
        """.trimMargin("|").toByteArray()
        )
    }
}
