# 🪶 Hazel: Minimal, and fast HTTP proxy to host files from any cloud storage provider.
# Copyright 2022-2023 Noelware <team@noelware.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Linting and Unit Testing
on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'issue/gh-**'
      - 'feat/**'
      - nightly
      - master

    paths-ignore:
      - '.github/**'
      - '.husky/**'
      - '.vscode/**'
      - 'assets/**'
      - 'locales/**'
      - 'docker/**'
      - '.dockerignore'
      - '.eslintignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'renovate.json'
  push:
    branches:
      - 'issue/gh-**'
      - 'feat/**'
      - nightly
      - master

    paths-ignore:
      - '.github/**'
      - '.husky/**'
      - '.vscode/**'
      - 'assets/**'
      - 'locales/**'
      - 'docker/**'
      - '.dockerignore'
      - '.eslintignore'
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'renovate.json'
jobs:
  spotless:
    name: Spotless [Java ${{matrix.java-version}}]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17, 19]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Java ${{matrix.java-version}}
        uses: actions/setup-java@v3
        with:
          java-version: ${{matrix.java-version}}
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Lint code-base with Spotless
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessCheck --no-daemon --scan

      - name: Compiles Kotlin source sets
        uses: gradle/gradle-build-action@v2
        with:
          arguments: compileKotlin --no-daemon --scan

      - name: Compiles Java source sets
        uses: gradle/gradle-build-action@v2
        with:
          arguments: compileJava --no-daemon --scan

      - name: Run unit and integration tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --no-daemon --scan
