# 🪶 hazel: Minimal, simple, and open source content delivery network made in Kotlin
# Copyright 2022 Noel <cutie@floofy.dev>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release (stable)
on:
  release:
    types:
      - published
jobs:
  release:
    name: Release (stable)
    runs-on: ubuntu-latest
    steps:
      - name: Checks out the repository
        uses: actions/checkout@v3

      - name: Get the current git tag to use
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

  deploy:
    name: Deploy on Kubernetes
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: Login to Kubernetes
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Get the current git tag to use
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: Set tag
        run: kubectl set image deployment/hazel hazel=auguwu/hazel:${{ steps.tag.outputs.tag }}

      - name: Deploy to the bot
        run: kubectl rollout status deployment/hazel
